### ISSUE TITLE
backend written in java, any plan add a go version for faster speed and easily deploy?

### ISSUE THREAD

**Issue by jinfagang** [WahidNasri/flutter-mqtt-chat-client#2]
backend written in java, any plan add a go version for faster speed and easily deploy? (i'd like willing to have a  try if there enough guidelines.

**Comment by WahidNasri** [comment]
Hi,
Thank you for your interest on flutter-mqtt-chat-client.

I added installation steps on the extension repository, [you can check it there](https://github.com/WahidNasri/hivemq-chat-extension#how-to-use).
Tell me if everything goes ok for you.

**Comment by jinfagang** [comment]
its helpful
